export default {
  SET_STATE: "SET_STATE",

  LOAD_MENU_REQ: "LOAD_MENU_REQ",
  LOAD_MENU_SUCCESS: "LOAD_MENU_SUCCESS",
  LOAD_MENU_FAILURE: "LOAD_MENU_FAILURE",


  GET_PROMOS_REQ: "GET_PROMOS_REQ",
  GET_PROMOS_SUCCESS: "GET_PROMOS_SUCCESS",
  GET_PROMOS_FAILURE: "GET_PROMOS_FAILURE",

}