export default {
  SET_STATE: "SET_STATE",

  LOAD_MENU_REQ: "LOAD_MENU_REQ",
  LOAD_MENU_SUCCESS: "LOAD_MENU_SUCCESS",
  LOAD_MENU_FAILURE: "LOAD_MENU_FAILURE",

  LOAD_RECOMMENDED_RESTAURANTS_REQ: "LOAD_RECOMMENDED_RESTAURANTS_REQ",
  LOAD_RECOMMENDED_RESTAURANTS_SUCCESS: "LOAD_RECOMMENDED_RESTAURANTS_SUCCESS",
  LOAD_RECOMMENDED_RESTAURANTS_FAILURE: "LOAD_RECOMMENDED_RESTAURANTS_FAILURE",


}