export default {
  SET_STATE: "SET_STATE",

  LOAD_RESTAURENT_DETAILS_REQ: "LOAD_RESTAURENT_DETAILS_REQ",
  LOAD_RESTAURENT_DETAILS_SUCCESS: "LOAD_RESTAURENT_DETAILS_SUCCESS",
  LOAD_RESTAURENT_DETAILS_FAILURE: "LOAD_RESTAURENT_DETAILS_FAILURE",


}